// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	app "github.com/YuriyNazarov/bannersRotator/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// BannersSelector is an autogenerated mock type for the BannersSelector type
type BannersSelector struct {
	mock.Mock
}

// SelectBanner provides a mock function with given fields: stats
func (_m *BannersSelector) SelectBanner(stats []app.BannerStat) (int, error) {
	ret := _m.Called(stats)

	var r0 int
	if rf, ok := ret.Get(0).(func([]app.BannerStat) int); ok {
		r0 = rf(stats)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]app.BannerStat) error); ok {
		r1 = rf(stats)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
