// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// StatsOutput is an autogenerated mock type for the StatsOutput type
type StatsOutput struct {
	mock.Mock
}

// Click provides a mock function with given fields: bannerID, slotID, groupID, clickTime
func (_m *StatsOutput) Click(bannerID int, slotID int, groupID int, clickTime time.Time) {
	_m.Called(bannerID, slotID, groupID, clickTime)
}

// View provides a mock function with given fields: bannerID, slotID, groupID, clickTime
func (_m *StatsOutput) View(bannerID int, slotID int, groupID int, clickTime time.Time) {
	_m.Called(bannerID, slotID, groupID, clickTime)
}
